-- A real taxonomy over the spec fields, replacing the three seeded MAJOR_TYPE buckets.
--
-- V40 could only carry over what major_type knew (Dimensions/Technical/Physical), which left ~290
-- unrelated fields in one "Technical" pile. This groups every spec field in the catalogue by the
-- concept it describes, so the part detail screen and the Spec Fields editor become navigable.
--
-- Groups are created per organisation, and only spec fields whose json_name is listed below move;
-- anything else (fields added since, another organisation's own fields) keeps its current group.
-- Dimensions already exists from V40 and is reused; Technical and Physical are dropped afterwards
-- if they end up empty.

INSERT INTO spec_group (organisation_id, name, display_order)
SELECT o.id, g.name, g.display_order
FROM organisation o
         CROSS JOIN (VALUES
    ('Dimensions', 0),
    ('Package & Mounting', 1),
    ('Materials & Finish', 2),
    ('Power Supply', 3),
    ('Voltage & Current Ratings', 4),
    ('Passive Values', 5),
    ('Semiconductor Characteristics', 6),
    ('Analog & Amplifier', 7),
    ('Data Conversion', 8),
    ('Logic & Digital', 9),
    ('Processor & Memory', 10),
    ('Interfaces & Channels', 11),
    ('Timing & Frequency', 12),
    ('Optoelectronics', 13),
    ('Switches, Relays & Connectors', 14),
    ('Protection & Isolation', 15),
    ('Thermal & Environmental', 16),
    ('Compliance & Lifecycle', 17),
    ('General', 18)
    ) AS g (name, display_order)
ON CONFLICT (organisation_id, name) DO UPDATE SET display_order = EXCLUDED.display_order;

-- Move each spec field into the group for its concept.
UPDATE spec_definition sd
SET group_id = sg.id
FROM (VALUES
    ('actuatorlength', 'Dimensions'),
    ('contactmatinglength', 'Dimensions'),
    ('contactpitch', 'Dimensions'),
    ('depth', 'Dimensions'),
    ('diameter', 'Dimensions'),
    ('height', 'Dimensions'),
    ('height_seated_max_', 'Dimensions'),
    ('leadlength', 'Dimensions'),
    ('leadpitch', 'Dimensions'),
    ('length', 'Dimensions'),
    ('matingpostlength', 'Dimensions'),
    ('pitch', 'Dimensions'),
    ('platingthickness', 'Dimensions'),
    ('rowspacing', 'Dimensions'),
    ('stackheight', 'Dimensions'),
    ('switchtravel', 'Dimensions'),
    ('terminalpitch', 'Dimensions'),
    ('thickness', 'Dimensions'),
    ('width', 'Dimensions'),
    ('case_package', 'Package & Mounting'),
    ('casecode_imperial_', 'Package & Mounting'),
    ('casecode_metric_', 'Package & Mounting'),
    ('connectortype', 'Package & Mounting'),
    ('fasteningtype', 'Package & Mounting'),
    ('mfgpackage_id', 'Package & Mounting'),
    ('mount', 'Package & Mounting'),
    ('numberofpins', 'Package & Mounting'),
    ('numberofrows', 'Package & Mounting'),
    ('numberofterminals', 'Package & Mounting'),
    ('orientation', 'Package & Mounting'),
    ('packagequantity', 'Package & Mounting'),
    ('packaging', 'Package & Mounting'),
    ('sealable', 'Package & Mounting'),
    ('shape', 'Package & Mounting'),
    ('shielding', 'Package & Mounting'),
    ('termination', 'Package & Mounting'),
    ('weight', 'Package & Mounting'),
    ('bodymaterial', 'Materials & Finish'),
    ('color', 'Materials & Finish'),
    ('composition', 'Materials & Finish'),
    ('contactmaterial', 'Materials & Finish'),
    ('contactplating', 'Materials & Finish'),
    ('corematerial', 'Materials & Finish'),
    ('dielectric', 'Materials & Finish'),
    ('dielectricmaterial', 'Materials & Finish'),
    ('flammabilityrating', 'Materials & Finish'),
    ('housingcolor', 'Materials & Finish'),
    ('housingmaterial', 'Materials & Finish'),
    ('insulation', 'Materials & Finish'),
    ('insulationcolor', 'Materials & Finish'),
    ('material', 'Materials & Finish'),
    ('plating', 'Materials & Finish'),
    ('shellfinish', 'Materials & Finish'),
    ('shellmaterial', 'Materials & Finish'),
    ('terminalmaterial', 'Materials & Finish'),
    ('current_output1', 'Power Supply'),
    ('current_output2', 'Power Supply'),
    ('dropoutvoltage', 'Power Supply'),
    ('dualsupplyvoltage', 'Power Supply'),
    ('efficiency', 'Power Supply'),
    ('inputcurrent', 'Power Supply'),
    ('inputvoltage', 'Power Supply'),
    ('inputvoltage_dc_', 'Power Supply'),
    ('mincurrentlimit', 'Power Supply'),
    ('numberofbatteries', 'Power Supply'),
    ('numberofcells', 'Power Supply'),
    ('numberofoutputphases', 'Power Supply'),
    ('numberofregulators', 'Power Supply'),
    ('numberofvoltagesmonitored', 'Power Supply'),
    ('operatingsupplycurrent', 'Power Supply'),
    ('operatingsupplyvoltage', 'Power Supply'),
    ('outputcurrent', 'Power Supply'),
    ('outputcurrentperchannel', 'Power Supply'),
    ('outputpower', 'Power Supply'),
    ('outputvoltage', 'Power Supply'),
    ('outputvoltageaccuracy', 'Power Supply'),
    ('overvoltagethreshold', 'Power Supply'),
    ('powerconsumption', 'Power Supply'),
    ('powerdissipation', 'Power Supply'),
    ('powerperelement', 'Power Supply'),
    ('powerrating', 'Power Supply'),
    ('quiescentcurrent', 'Power Supply'),
    ('referencevoltage', 'Power Supply'),
    ('reset', 'Power Supply'),
    ('resetthresholdvoltage', 'Power Supply'),
    ('resettimeout', 'Power Supply'),
    ('supplycurrent', 'Power Supply'),
    ('supplytype', 'Power Supply'),
    ('supplyvoltage', 'Power Supply'),
    ('supplyvoltage_dc_', 'Power Supply'),
    ('switchingfrequency', 'Power Supply'),
    ('synchronousrectifier', 'Power Supply'),
    ('topology', 'Power Supply'),
    ('undervoltagethreshold', 'Power Supply'),
    ('voltage_output1', 'Power Supply'),
    ('voltage_output2', 'Power Supply'),
    ('breakdownvoltage', 'Voltage & Current Ratings'),
    ('current', 'Voltage & Current Ratings'),
    ('currentrating', 'Voltage & Current Ratings'),
    ('dccurrent', 'Voltage & Current Ratings'),
    ('fusecurrent', 'Voltage & Current Ratings'),
    ('holdcurrent', 'Voltage & Current Ratings'),
    ('maxi_ovoltage', 'Voltage & Current Ratings'),
    ('ratings', 'Voltage & Current Ratings'),
    ('rmscurrent_irms_', 'Voltage & Current Ratings'),
    ('testcurrent', 'Voltage & Current Ratings'),
    ('voltage', 'Voltage & Current Ratings'),
    ('voltagerating', 'Voltage & Current Ratings'),
    ('voltagerating_ac_', 'Voltage & Current Ratings'),
    ('voltagerating_dc_', 'Voltage & Current Ratings'),
    ('voltagetolerance', 'Voltage & Current Ratings'),
    ('workingvoltage', 'Voltage & Current Ratings'),
    ('capacitance', 'Passive Values'),
    ('dcresistance_dcr_', 'Passive Values'),
    ('dissipationfactor', 'Passive Values'),
    ('esr_equivalentseriesresistance_', 'Passive Values'),
    ('impedance', 'Passive Values'),
    ('inductance', 'Passive Values'),
    ('inductancetolerance', 'Passive Values'),
    ('insulationresistance', 'Passive Values'),
    ('loadcapacitance', 'Passive Values'),
    ('numberofresistors', 'Passive Values'),
    ('numberofturns', 'Passive Values'),
    ('qfactor', 'Passive Values'),
    ('resistance', 'Passive Values'),
    ('ripplecurrent', 'Passive Values'),
    ('saturationcurrent', 'Passive Values'),
    ('selfresonantfrequency', 'Passive Values'),
    ('seriesresistance', 'Passive Values'),
    ('taper', 'Passive Values'),
    ('temperaturecoefficient', 'Passive Values'),
    ('testfrequency', 'Passive Values'),
    ('tolerance', 'Passive Values'),
    ('averagerectifiedcurrent', 'Semiconductor Characteristics'),
    ('collectorbasevoltage_vcbo_', 'Semiconductor Characteristics'),
    ('collectoremitterbreakdownvoltage', 'Semiconductor Characteristics'),
    ('collectoremittersaturationvoltage', 'Semiconductor Characteristics'),
    ('collectoremittervoltage_vceo_', 'Semiconductor Characteristics'),
    ('continuouscollectorcurrent', 'Semiconductor Characteristics'),
    ('continuousdraincurrent_id_', 'Semiconductor Characteristics'),
    ('diodetype', 'Semiconductor Characteristics'),
    ('draintosourcebreakdownvoltage', 'Semiconductor Characteristics'),
    ('draintosourceresistance', 'Semiconductor Characteristics'),
    ('draintosourcevoltage_vdss_', 'Semiconductor Characteristics'),
    ('emitterbasevoltage_vebo_', 'Semiconductor Characteristics'),
    ('forwardcurrent', 'Semiconductor Characteristics'),
    ('forwardvoltage', 'Semiconductor Characteristics'),
    ('gatetosourcevoltage_vgs_', 'Semiconductor Characteristics'),
    ('hfemin', 'Semiconductor Characteristics'),
    ('leakagecurrent', 'Semiconductor Characteristics'),
    ('maxcollectorcurrent', 'Semiconductor Characteristics'),
    ('maxforwardsurgecurrent_ifsm_', 'Semiconductor Characteristics'),
    ('maxrepetitivereversevoltage_vrrm_', 'Semiconductor Characteristics'),
    ('maxreverseleakagecurrent', 'Semiconductor Characteristics'),
    ('maxsurgecurrent', 'Semiconductor Characteristics'),
    ('nominalvgs', 'Semiconductor Characteristics'),
    ('on_stateresistance', 'Semiconductor Characteristics'),
    ('peaknon_repetitivesurgecurrent', 'Semiconductor Characteristics'),
    ('peakreversecurrent', 'Semiconductor Characteristics'),
    ('rdsonmax', 'Semiconductor Characteristics'),
    ('recoverytime', 'Semiconductor Characteristics'),
    ('reversebreakdownvoltage', 'Semiconductor Characteristics'),
    ('reverserecoverytime', 'Semiconductor Characteristics'),
    ('reversevoltage', 'Semiconductor Characteristics'),
    ('reversevoltage_dc_', 'Semiconductor Characteristics'),
    ('thresholdvoltage', 'Semiconductor Characteristics'),
    ('transitionfrequency', 'Semiconductor Characteristics'),
    ('zenercurrent', 'Semiconductor Characteristics'),
    ('zenervoltage', 'Semiconductor Characteristics'),
    ('bandwidth', 'Analog & Amplifier'),
    ('commonmoderejectionratio', 'Analog & Amplifier'),
    ('gain', 'Analog & Amplifier'),
    ('gainbandwidthproduct', 'Analog & Amplifier'),
    ('inputbiascurrent', 'Analog & Amplifier'),
    ('inputcapacitance', 'Analog & Amplifier'),
    ('inputoffsetvoltage_vos_', 'Analog & Amplifier'),
    ('insertionloss_db_', 'Analog & Amplifier'),
    ('linearity', 'Analog & Amplifier'),
    ('nominalgainbandwidthproduct', 'Analog & Amplifier'),
    ('numberofamplifiers', 'Analog & Amplifier'),
    ('powersupplyrejectionratio_psrr_', 'Analog & Amplifier'),
    ('slewrate', 'Analog & Amplifier'),
    ('unitygainbandwidthproduct', 'Analog & Amplifier'),
    ('voltagegain', 'Analog & Amplifier'),
    ('accuracy', 'Data Conversion'),
    ('adcchannelsresolution', 'Data Conversion'),
    ('dacchannelsresolution', 'Data Conversion'),
    ('integralnonlinearity_inl_', 'Data Conversion'),
    ('numberofa_dconverters', 'Data Conversion'),
    ('numberofadcchannels', 'Data Conversion'),
    ('numberofbits', 'Data Conversion'),
    ('numberofbitsperelement', 'Data Conversion'),
    ('numberofconverters', 'Data Conversion'),
    ('numberofd_aconverters', 'Data Conversion'),
    ('numberofdacchannels', 'Data Conversion'),
    ('resolution', 'Data Conversion'),
    ('settlingtime', 'Data Conversion'),
    ('clockedgetriggertype', 'Logic & Digital'),
    ('clocksync', 'Logic & Digital'),
    ('datapolarity', 'Logic & Digital'),
    ('differentialoutput', 'Logic & Digital'),
    ('highleveloutputcurrent', 'Logic & Digital'),
    ('logicfunction', 'Logic & Digital'),
    ('lowleveloutputcurrent', 'Logic & Digital'),
    ('numberofgates', 'Logic & Digital'),
    ('numberofinputlines', 'Logic & Digital'),
    ('numberofinputs', 'Logic & Digital'),
    ('numberoflines', 'Logic & Digital'),
    ('numberofmacrocells', 'Logic & Digital'),
    ('numberofoutputlines', 'Logic & Digital'),
    ('numberofoutputs', 'Logic & Digital'),
    ('outputconfiguration', 'Logic & Digital'),
    ('outputtype', 'Logic & Digital'),
    ('propagationdelay', 'Logic & Digital'),
    ('schmitttriggerinput', 'Logic & Digital'),
    ('speedgrade', 'Logic & Digital'),
    ('sync_async', 'Logic & Digital'),
    ('accesstime', 'Processor & Memory'),
    ('addressbuswidth', 'Processor & Memory'),
    ('corearchitecture', 'Processor & Memory'),
    ('databuswidth', 'Processor & Memory'),
    ('density', 'Processor & Memory'),
    ('eeprommemorysize', 'Processor & Memory'),
    ('flashmemorysize', 'Processor & Memory'),
    ('memorysize', 'Processor & Memory'),
    ('memorytype', 'Processor & Memory'),
    ('numberofi_os', 'Processor & Memory'),
    ('numberofinterrupts', 'Processor & Memory'),
    ('numberofprogrammablei_o', 'Processor & Memory'),
    ('numberoftimers_counters', 'Processor & Memory'),
    ('numberofwords', 'Processor & Memory'),
    ('peripherals', 'Processor & Memory'),
    ('ramsize', 'Processor & Memory'),
    ('watchdogtimer', 'Processor & Memory'),
    ('wordsize', 'Processor & Memory'),
    ('baudrate', 'Interfaces & Channels'),
    ('datarate', 'Interfaces & Channels'),
    ('input', 'Interfaces & Channels'),
    ('interface', 'Interfaces & Channels'),
    ('numberofbidirectionalchannels', 'Interfaces & Channels'),
    ('numberofchannels', 'Interfaces & Channels'),
    ('numberofdrivers', 'Interfaces & Channels'),
    ('numberofi2cchannels', 'Interfaces & Channels'),
    ('numberofports', 'Interfaces & Channels'),
    ('numberofreceivers', 'Interfaces & Channels'),
    ('numberofspichannels', 'Interfaces & Channels'),
    ('numberoftransceivers', 'Interfaces & Channels'),
    ('numberoftransmitters', 'Interfaces & Channels'),
    ('numberofuartchannels', 'Interfaces & Channels'),
    ('numberofpwmchannels', 'Interfaces & Channels'),
    ('numberofunidirectionalchannels', 'Interfaces & Channels'),
    ('numberofusartchannels', 'Interfaces & Channels'),
    ('numberofusbchannels', 'Interfaces & Channels'),
    ('receiverhysteresis', 'Interfaces & Channels'),
    ('simplex_duplex', 'Interfaces & Channels'),
    ('usbstandard', 'Interfaces & Channels'),
    ('dutycycle', 'Timing & Frequency'),
    ('falltime', 'Timing & Frequency'),
    ('frequency', 'Timing & Frequency'),
    ('frequencystability', 'Timing & Frequency'),
    ('frequencytolerance', 'Timing & Frequency'),
    ('operatetime', 'Timing & Frequency'),
    ('oscillatortype', 'Timing & Frequency'),
    ('outputfrequency', 'Timing & Frequency'),
    ('pll', 'Timing & Frequency'),
    ('releasetime', 'Timing & Frequency'),
    ('responsetime', 'Timing & Frequency'),
    ('risetime', 'Timing & Frequency'),
    ('timeformat', 'Timing & Frequency'),
    ('turn_offdelaytime', 'Timing & Frequency'),
    ('turn_ondelaytime', 'Timing & Frequency'),
    ('currenttransferratio', 'Optoelectronics'),
    ('darkcurrent', 'Optoelectronics'),
    ('dominantwavelength', 'Optoelectronics'),
    ('illuminationtype', 'Optoelectronics'),
    ('lenscolor', 'Optoelectronics'),
    ('lensstyle', 'Optoelectronics'),
    ('lenstransparency', 'Optoelectronics'),
    ('life_hours_', 'Optoelectronics'),
    ('luminousintensity', 'Optoelectronics'),
    ('numberofleds', 'Optoelectronics'),
    ('peakwavelength', 'Optoelectronics'),
    ('viewingangle', 'Optoelectronics'),
    ('coilcurrent', 'Switches, Relays & Connectors'),
    ('coilpower', 'Switches, Relays & Connectors'),
    ('coilresistance', 'Switches, Relays & Connectors'),
    ('coiltype', 'Switches, Relays & Connectors'),
    ('coilvoltage_dc_', 'Switches, Relays & Connectors'),
    ('contactcurrentrating', 'Switches, Relays & Connectors'),
    ('contactgender', 'Switches, Relays & Connectors'),
    ('contactresistance', 'Switches, Relays & Connectors'),
    ('contactstyle', 'Switches, Relays & Connectors'),
    ('contactvoltagerating_ac_', 'Switches, Relays & Connectors'),
    ('electricallife', 'Switches, Relays & Connectors'),
    ('gender', 'Switches, Relays & Connectors'),
    ('life_cycles_', 'Switches, Relays & Connectors'),
    ('mechanicallife', 'Switches, Relays & Connectors'),
    ('numberofcontacts', 'Switches, Relays & Connectors'),
    ('numberofpoles', 'Switches, Relays & Connectors'),
    ('numberofpositions', 'Switches, Relays & Connectors'),
    ('operatingforce', 'Switches, Relays & Connectors'),
    ('relaytype', 'Switches, Relays & Connectors'),
    ('switchfunction', 'Switches, Relays & Connectors'),
    ('throwconfiguration', 'Switches, Relays & Connectors'),
    ('clampingvoltage', 'Protection & Isolation'),
    ('esdprotection', 'Protection & Isolation'),
    ('faultprotection', 'Protection & Isolation'),
    ('isolation', 'Protection & Isolation'),
    ('isolationvoltage', 'Protection & Isolation'),
    ('peakpulsecurrent', 'Protection & Isolation'),
    ('peakpulsepower', 'Protection & Isolation'),
    ('powerlineprotection', 'Protection & Isolation'),
    ('radiationhardening', 'Protection & Isolation'),
    ('reversestandoffvoltage', 'Protection & Isolation'),
    ('timetotrip', 'Protection & Isolation'),
    ('tripcurrent', 'Protection & Isolation'),
    ('ambienttemperaturerange', 'Thermal & Environmental'),
    ('maxjunctiontemperature', 'Thermal & Environmental'),
    ('naturalthermalresistance', 'Thermal & Environmental'),
    ('operatingtemperature', 'Thermal & Environmental'),
    ('temperaturegrade', 'Thermal & Environmental'),
    ('ProjectedEOLDate', 'Compliance & Lifecycle'),
    ('approvals', 'Compliance & Lifecycle'),
    ('china_rohs', 'Compliance & Lifecycle'),
    ('countryofassembly', 'Compliance & Lifecycle'),
    ('countryoffabrication', 'Compliance & Lifecycle'),
    ('countryoforigin', 'Compliance & Lifecycle'),
    ('eccncode', 'Compliance & Lifecycle'),
    ('evaluationkit', 'Compliance & Lifecycle'),
    ('glowwirecompliant', 'Compliance & Lifecycle'),
    ('halogenfree', 'Compliance & Lifecycle'),
    ('hscode', 'Compliance & Lifecycle'),
    ('htscode', 'Compliance & Lifecycle'),
    ('introdate', 'Compliance & Lifecycle'),
    ('leadfree', 'Compliance & Lifecycle'),
    ('lifecyclestatus', 'Compliance & Lifecycle'),
    ('ltb_date', 'Compliance & Lifecycle'),
    ('ltd_date', 'Compliance & Lifecycle'),
    ('manufacturerlifecyclestatus', 'Compliance & Lifecycle'),
    ('militarystandard', 'Compliance & Lifecycle'),
    ('reachsvhc', 'Compliance & Lifecycle'),
    ('rohs', 'Compliance & Lifecycle'),
    ('scheduleB', 'Compliance & Lifecycle'),
    ('yeol', 'Compliance & Lifecycle'),
    ('circuittype', 'General'),
    ('direction', 'General'),
    ('elementconfiguration', 'General'),
    ('family', 'General'),
    ('features', 'General'),
    ('independentcircuits', 'General'),
    ('numberofcircuits', 'General'),
    ('numberofelements', 'General'),
    ('polarity', 'General'),
    ('sensortype', 'General'),
    ('type', 'General')
    ) AS m (json_name, group_name)
         JOIN spec_group sg ON sg.name = m.group_name
WHERE sd.json_name = m.json_name
  AND sg.organisation_id = sd.organisation_id;

-- The old buckets are only removed once nothing is left in them.
DELETE FROM spec_group sg
WHERE sg.name IN ('Technical', 'Physical')
  AND NOT EXISTS (SELECT 1 FROM spec_definition sd WHERE sd.group_id = sg.id);
