-- Seed a standard, Octopart/Digi-Key-style electronic-component category taxonomy.
-- Fresh-replace: the existing category rows are ad-hoc demo/test data, no part references any
-- category (part.category_id all NULL) and category_spec was wiped in V6, so a clean wipe is safe.
-- Explicit ids/parent_ids are used for determinism (the table is emptied first). All rows are
-- inserted in a single statement, so self-referencing parent_ids resolve regardless of order.

DELETE FROM category_spec;
DELETE FROM category;

INSERT INTO category (id, name, description, parent_id) VALUES
-- ============================ Passive Components ============================
(100, 'Passive Components', 'Resistors, capacitors, inductors and other non-amplifying components', NULL),
(110, 'Resistors', 'Fixed and variable resistive components', 100),
(111, 'Fixed Resistors', 'Through-hole and SMD fixed-value resistors', 110),
(112, 'Potentiometers & Trimmers', 'Adjustable resistors and trimming potentiometers', 110),
(113, 'Resistor Networks & Arrays', 'Multiple resistors in a single package', 110),
(114, 'Thermistors', 'Temperature-dependent resistors (NTC/PTC)', 110),
(115, 'Varistors', 'Voltage-dependent resistors (MOV) for surge suppression', 110),
(116, 'Current Sense Resistors', 'Low-value precision resistors for current measurement', 110),
(120, 'Capacitors', 'Energy-storage and decoupling capacitors', 100),
(121, 'Ceramic Capacitors', 'MLCC and disc ceramic capacitors', 120),
(122, 'Aluminum Electrolytic Capacitors', 'Polarized aluminum electrolytic capacitors', 120),
(123, 'Tantalum Capacitors', 'Polarized tantalum capacitors', 120),
(124, 'Film Capacitors', 'Polyester, polypropylene and other film capacitors', 120),
(125, 'Supercapacitors', 'High-capacitance double-layer / EDLC capacitors', 120),
(126, 'Variable Capacitors', 'Trimmer and tuning capacitors', 120),
(130, 'Inductors', 'Coils, chokes and magnetic components', 100),
(131, 'Fixed Inductors', 'Through-hole and SMD fixed inductors', 130),
(132, 'Ferrite Beads', 'High-frequency noise suppression beads', 130),
(133, 'Common-Mode Chokes', 'Common-mode noise filtering inductors', 130),
(140, 'Transformers', 'Power and signal transformers', 100),
(150, 'Crystals, Oscillators & Resonators', 'Frequency-control components', 100),
(151, 'Crystals', 'Quartz crystal units', 150),
(152, 'Oscillators', 'Packaged clock oscillators (XO/TCXO/VCXO)', 150),
(153, 'Resonators', 'Ceramic resonators', 150),
(160, 'EMI Filters & Ferrites', 'EMI/RFI suppression filters and ferrite cores', 100),

-- ============================ Semiconductors ============================
(200, 'Semiconductors', 'Active devices: diodes, transistors and integrated circuits', NULL),
(210, 'Diodes', 'Two-terminal semiconductor rectifying devices', 200),
(211, 'Rectifier Diodes', 'General-purpose and fast-recovery rectifiers', 210),
(212, 'Schottky Diodes', 'Low forward-drop Schottky barrier diodes', 210),
(213, 'Zener Diodes', 'Voltage-reference / regulation diodes', 210),
(214, 'TVS Diodes', 'Transient-voltage-suppression diodes', 210),
(215, 'Small-Signal Diodes', 'Switching and signal diodes', 210),
(216, 'Bridge Rectifiers', 'Integrated full-wave rectifier bridges', 210),
(220, 'Transistors', 'Three-terminal amplifying / switching devices', 200),
(221, 'Bipolar (BJT)', 'NPN/PNP bipolar junction transistors', 220),
(222, 'MOSFET', 'Metal-oxide-semiconductor field-effect transistors', 220),
(223, 'JFET', 'Junction field-effect transistors', 220),
(224, 'IGBT', 'Insulated-gate bipolar transistors', 220),
(225, 'Darlington', 'Darlington-pair transistors', 220),
(230, 'Thyristors', 'Latching power-control devices', 200),
(231, 'SCR', 'Silicon-controlled rectifiers', 230),
(232, 'TRIAC', 'Bidirectional AC switches', 230),
(233, 'DIAC', 'Bidirectional trigger diodes', 230),
(240, 'Integrated Circuits', 'Monolithic integrated circuits', 200),
(250, 'Logic ICs', 'Digital logic functions (74xx/40xx families and variants)', 240),
(251, 'Gates', 'Basic logic gates: NAND, NOR, AND, OR, XOR, NOT', 250),
(252, 'Flip-Flops & Latches', 'Bistable storage elements: D, JK, SR and transparent latches', 250),
(253, 'Counters', 'Binary and BCD ripple and synchronous counters', 250),
(254, 'Shift Registers', 'Serial and parallel shift registers', 250),
(255, 'Buffers & Drivers', 'Line drivers, bus buffers, tri-state and open-collector drivers', 250),
(256, 'Multiplexers & Demultiplexers', 'Data selectors and distributors', 250),
(257, 'Decoders & Encoders', 'BCD decoders, 7-segment drivers, priority encoders', 250),
(258, 'Arithmetic', 'Adders, comparators, ALUs and carry generators', 250),
(260, 'Analog ICs', 'Linear / analog signal-processing ICs', 240),
(261, 'Operational Amplifiers', 'Op-amps and instrumentation amplifiers', 260),
(262, 'Comparators', 'Voltage comparators', 260),
(263, 'Voltage References', 'Precision voltage references', 260),
(264, 'Analog Switches & Multiplexers', 'Analog switches and multiplexers', 260),
(265, 'Data Converters (ADC/DAC)', 'Analog-to-digital and digital-to-analog converters', 260),
(270, 'Power Management ICs', 'Voltage regulation and power-control ICs', 240),
(271, 'Linear Regulators (LDO)', 'Low-dropout and linear voltage regulators', 270),
(272, 'Switching Regulators / DC-DC', 'Buck, boost and buck-boost switching regulators', 270),
(273, 'Voltage Supervisors & Resets', 'Supervisory, reset and brown-out detection ICs', 270),
(274, 'Battery Management', 'Charger and battery-management ICs', 270),
(275, 'Motor Drivers', 'Brushed, brushless and stepper motor drivers', 270),
(276, 'Gate Drivers', 'MOSFET/IGBT gate-driver ICs', 270),
(280, 'Microcontrollers & Processors', 'Programmable processing devices', 240),
(281, 'Microcontrollers (MCU)', 'Single-chip microcontrollers', 280),
(282, 'Microprocessors (MPU)', 'Application microprocessors', 280),
(283, 'FPGA / CPLD', 'Field-programmable gate arrays and complex PLDs', 280),
(284, 'DSP', 'Digital signal processors', 280),
(290, 'Memory ICs', 'Volatile and non-volatile memory', 240),
(291, 'EEPROM', 'Electrically-erasable programmable ROM', 290),
(292, 'Flash', 'NOR/NAND flash memory', 290),
(293, 'SRAM / DRAM', 'Static and dynamic RAM', 290),
(300, 'Interface ICs', 'Communication and bus interface ICs', 240),
(301, 'USB', 'USB controllers and transceivers', 300),
(302, 'CAN / LIN', 'CAN and LIN bus transceivers', 300),
(303, 'RS-232 / RS-485', 'Serial line transceivers', 300),
(304, 'I2C / SPI', 'I²C and SPI expanders and bridges', 300),
(305, 'Ethernet / PHY', 'Ethernet controllers and PHYs', 300),
(310, 'Clock & Timing ICs', 'Timing and clock-generation ICs', 240),
(311, 'Timers', 'Programmable timers (e.g. 555-type)', 310),
(312, 'Real-Time Clocks (RTC)', 'Real-time clock and calendar ICs', 310),
(313, 'Clock Generators', 'Clock generators and buffers', 310),
(320, 'RF / Wireless ICs', 'RF transceivers and wireless front-ends', 240),

-- ============================ Optoelectronics ============================
(400, 'Optoelectronics', 'Light-emitting and light-sensing components', NULL),
(410, 'LEDs', 'Light-emitting diodes', 400),
(411, 'Standard LEDs', 'Single-color indicator LEDs', 410),
(412, 'RGB LEDs', 'Multi-color and addressable RGB LEDs', 410),
(413, 'High-Power LEDs', 'Lighting-grade high-power LEDs', 410),
(414, 'IR / UV LEDs', 'Infrared and ultraviolet emitters', 410),
(420, 'Displays', 'Visual display components', 400),
(421, '7-Segment Displays', 'Numeric LED segment displays', 420),
(422, 'LCD', 'Liquid-crystal displays', 420),
(423, 'OLED', 'Organic LED displays', 420),
(424, 'LED Matrix', 'Dot-matrix LED displays', 420),
(430, 'Optocouplers & Optoisolators', 'Optically-isolated signal couplers', 400),
(440, 'Photodiodes & Phototransistors', 'Light-sensing semiconductors', 400),
(450, 'Laser Diodes', 'Semiconductor laser emitters', 400),

-- ============================ Connectors ============================
(500, 'Connectors', 'Electrical connectors and interconnect', NULL),
(510, 'Headers & Wire-to-Board', 'Pin headers and wire-to-board connectors', 500),
(520, 'Board-to-Board', 'Board-to-board mating connectors', 500),
(530, 'Terminal Blocks', 'Screw and spring terminal blocks', 500),
(540, 'USB / Audio / Video', 'USB, audio jack and video connectors', 500),
(550, 'RF / Coaxial', 'SMA, BNC and other coaxial connectors', 500),
(560, 'Card Connectors', 'SD, SIM and memory-card sockets', 500),
(570, 'Power Connectors', 'Barrel jacks and power connectors', 500),
(580, 'FFC / FPC', 'Flat-flex and flexible printed-circuit connectors', 500),

-- ============================ Electromechanical ============================
(600, 'Electromechanical', 'Switches, relays and motion components', NULL),
(610, 'Switches', 'Manually-operated switches', 600),
(611, 'Tactile Switches', 'Momentary tactile pushbuttons', 610),
(612, 'Toggle Switches', 'Lever toggle switches', 610),
(613, 'Slide Switches', 'Sliding-actuator switches', 610),
(614, 'Rotary Switches', 'Rotary-position switches', 610),
(615, 'DIP Switches', 'PCB-mount DIP switches', 610),
(616, 'Pushbutton Switches', 'Panel and PCB pushbuttons', 610),
(620, 'Relays', 'Electrically-operated switches', 600),
(621, 'Signal Relays', 'Low-current signal relays', 620),
(622, 'Power Relays', 'High-current power relays', 620),
(623, 'Solid-State Relays', 'Semiconductor-based relays', 620),
(630, 'Motors & Actuators', 'DC, stepper and servo motors and actuators', 600),
(640, 'Fans & Thermal Management', 'Cooling and thermal components', 600),
(641, 'Heatsinks', 'Passive heat sinks', 640),
(642, 'Fans', 'Cooling fans and blowers', 640),
(650, 'Buzzers, Speakers & Microphones', 'Audio transducers', 600),

-- ============================ Sensors ============================
(700, 'Sensors', 'Sensing and measurement components', NULL),
(710, 'Temperature Sensors', 'Temperature-sensing devices', 700),
(720, 'Pressure Sensors', 'Pressure and force sensors', 700),
(730, 'Motion & IMU', 'Accelerometers, gyroscopes and IMUs', 700),
(740, 'Light & Proximity', 'Ambient-light and proximity sensors', 700),
(750, 'Current & Hall-Effect', 'Current and magnetic-field sensors', 700),
(760, 'Humidity Sensors', 'Relative-humidity sensors', 700),
(770, 'Gas Sensors', 'Gas and air-quality sensors', 700),

-- ============================ Power Sources & Protection ============================
(800, 'Power Sources & Protection', 'Power supply and circuit-protection components', NULL),
(810, 'Batteries & Holders', 'Cells, batteries and battery holders', 800),
(820, 'AC-DC Power Supplies', 'Mains AC-DC power modules', 800),
(830, 'DC-DC Converter Modules', 'Packaged DC-DC converter modules', 800),
(840, 'Fuses', 'One-time overcurrent fuses', 800),
(850, 'Resettable (PTC) Fuses', 'Polyfuse / PTC resettable protection', 800),
(860, 'Circuit Protection', 'Surge, ESD and other protection devices', 800),

-- ============================ Cables & Wire ============================
(900, 'Cables & Wire', 'Wire, cable and related materials', NULL),
(910, 'Hook-up Wire', 'Single-conductor hook-up wire', 900),
(920, 'Cable Assemblies', 'Pre-terminated cable assemblies', 900),
(930, 'Heat-Shrink & Sleeving', 'Insulation tubing and sleeving', 900),

-- ============================ Hardware & Prototyping ============================
(1000, 'Hardware & Prototyping', 'Mechanical hardware and prototyping supplies', NULL),
(1010, 'PCBs & Protoboards', 'Bare PCBs, perfboard and stripboard', 1000),
(1020, 'Standoffs, Spacers & Screws', 'Mechanical fasteners and spacers', 1000),
(1030, 'Enclosures', 'Project boxes and enclosures', 1000),
(1040, 'Breadboards & Jumper Wires', 'Solderless breadboards and jumpers', 1000),
(1050, 'IC Sockets', 'DIP/PLCC sockets and pin receptacles', 1000),

-- ============================ Modules & Development Boards ============================
(1100, 'Modules & Development Boards', 'Assembled modules and dev boards', NULL),
(1110, 'Microcontroller Boards', 'Arduino, ESP and other MCU dev boards', 1100),
(1120, 'Wireless Modules', 'Wi-Fi, Bluetooth, LoRa and other RF modules', 1100),
(1130, 'Sensor Modules', 'Breakout boards for sensors', 1100),
(1140, 'Display Modules', 'Breakout boards for displays', 1100),

-- ============================ Catch-all ============================
(1200, 'Uncategorized / Misc', 'Parts not yet classified', NULL);

-- Realign the sequence so app-created categories get ids above the seeded block.
SELECT setval('category_id_seq', (SELECT MAX(id) FROM category));
